///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String firebaseworkEmployeeUpdate = 'lib/firebasework/EmployeeUpdate.dart';
  static const String firebaseworkFetchdata = 'lib/firebasework/fetchdata.dart';
  static const String firebaseworkViewEmployee = 'lib/firebasework/ViewEmployee.dart';
  static const String generatedAssets = 'lib/generated/assets.dart';
  static const String libMain = 'lib/main.dart';
  static const String mixinEmailvalidator = 'lib/mixin/emailvalidator.dart';
  static const String mixinValidationmixin = 'lib/mixin/validationmixin.dart';
  static const String modelsAlbums = 'lib/models/Albums.dart';
  static const String screensFinalpost = 'lib/screens/finalpost.dart';
  static const String screensLoginpagescreen = 'lib/screens/loginpagescreen.dart';
  static const String screensLoginscreen = 'lib/screens/loginscreen.dart';
  static const String screensSignup = 'lib/screens/signup.dart';
  static const String screensSignupscreen = 'lib/screens/signupscreen.dart';
}
